### ISSUE TITLE
Create page

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#13]
## Value Proposition
As a tutor, I need the ability to enter my learning content in individual steps in order to create easy-to-follow step-by-step tutorials.

## Description
![capstone-userstory-07](https://user-images.githubusercontent.com/71948045/197350990-40baa43b-f4fb-4fe8-aadb-30fb65c73b10.jpg)

## Acceptance Criteria
- [x] shows the headline "Create a new tutorial"
- [x] shows a `title card` with the possibility to enter the title of the tutorial
- [x] shows a `step card` with the possibility to enter the title of the step, a description text and an URL to an image
- [x] shows a `add step` button that creates a new `step card` for another step
- [x] the `step cards` display the text "Step <x>" according to their step number

## Tasks
- [x] create a new branch
- [x] create `create` page component
- [x] create a `CreateForm` component that contains input fields for tutorial title, step title, image URL and description
- [x] include the form in the `create`page
- [x] add a `useState` for the step count
- [x] add an `add step` button
- [x] create functionality to generate a new `form card` for another step when `add step` button is clicked

**Comment by CathrinTruchan** [comment]
Hi Kai, 
very nice user story!
What is missing is a button to submit the steps. Or is that part of another user story?

**Comment by kai-franke** [comment]
I'm glad you asked about it, @CathrinTruchan ! You'll find the feature you want in this next user story: https://github.com/kai-franke/capstone-project/issues/14
