### ISSUE TITLE
Create page / save function / part 1

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#14]
> This user story was split because the PR became too big. Part 2 can be found [here](https://github.com/kai-franke/capstone-project/issues/22).

## Value Proposition
As a tutor, I want the tutorial data I enter to conform to the specified format so that it can be saved in the future.

## Description
![capstone-userstory-08](https://user-images.githubusercontent.com/71948045/197354350-1f836baf-54d0-44eb-ad8d-e12cd448a75f.png)

## Acceptance Criteria
- [x] shows a `finish creating` button
- [x] when this button is clicked an object is created which holds the entered data 
- [x] the input field `Tutorial title` must not be empty, must contain at least 5 and at most 60 characters
- [x] the input field `Step title` must not contain more than 60 characters
- [x] the input field `Step description` must not contain more than 300 characters
- [x] the input field `Picture URL` may only accept input in the form of a valid URL, which must end on `.gif`, `.jpg`, `.jpeg`, `.jfif`, `.pjpeg`, `.pjp`, `.png`, `.webp`.

## Tasks
- [x] make `Tutorial title` required, set minlength and maxlength
- [x] set maxlength for `Step title` 
- [x] set maxlength for `Step description`
- [x] set `type='url` and set pattern for `Picture URL`
- [x] add a `submit` button and name it `finish creating` 
- [x] make use of the entered data and convert it to the following structure:
```
{
    id: nanoid(),
    name: "Tutorial name",
    cover: "url of last step's image",
    slug: "tutorial-name-converted-to-lowercase-and-with-dashes",
    steps: [
        {
            step: 0,
        },
        {
            step: 1,
            title: "Step 1 title",
            description: "Step 1 description text",
            img: "Step 1 image url",
        },
        ...
    ],
}
```

**Comment by PhilippWeiss85** [comment]
Hey Kai, LGTM!
One suggestion: I would probably write "... to save the new created tutorial" instead of "... to save the entered tutorial steps". This would fit in better with the layout of your wireframe. However, complain at a high level :)

**Comment by kai-franke** [comment]
I don't see a complaint here - I see a very valuable suggestion for improvement, for which I am very grateful, @PhilippWeiss85 !

**Comment by Kheirah** [comment]
Super detailed story, I love it ❤️ 
I could follow along your every step. I'm looking forward to seeing how you implement your story!

**Comment by kai-franke** [comment]
> Super detailed story, I love it ❤️ I could follow along your every step. I'm looking forward to seeing how you implement your story!

Thanks so much for your encouraging feedback, @Kheirah ! 😃

**Comment by kai-franke** [comment]
This user story was split because the PR became too big. Part 2 can be found https://github.com/kai-franke/capstone-project/issues/22.
