### ISSUE TITLE
Create page / input limitations

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#17]
## Value Proposition
As a tutor, I would like to have helpful hints and limitations when entering my tutorial content so that my tutorials can be processed correctly and properly displayed.

## Description
// Insert Wire Frame

## Acceptance Criteria
- [ ] Input field `Tutorial title` must not be empty, must contain at least 5 and at most 60 characters
- [ ] Input field `Step title` must not contain more than 60 characters
- [ ] Input field `Step description` must not contain more than 300 characters
- [ ] Input field `Picture URL` may only accept input in the form of a valid URL, which must end on ".jpg".

## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
