### ISSUE TITLE
Library page

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#2]
## Value Proposition
As a tutee[^1], I would like to have an overview of the tutorials available to me so I can choose which content I want to learn.

## Description
![capstone-userstory-01](https://user-images.githubusercontent.com/71948045/196129185-f21775c9-2c01-48a2-a19f-0567a6004aa7.png)

## Acceptance Criteria
- [x] shows the headline 'MY TUTORIALS'
- [x] shows a list with names and images of all available tutorial
- [x] shows the message "No more tutorials"

## Tasks
- [x] create a new branch
- [x] create a `LibraryPage` component
- [x] create a `TutorialList` and a `TutorialListItem` component
- [x] add `h2` 'MY TUTORIALS'
- [x] create an array with demo content:
>```
>const initialTutorials = [
>  {
>    'id': 'b74d7e1c-acc4-4f65-bfd9-aeaa70dd6878',
>     'name': 'baking bread',
>     'img': 'url'
>  },
>  {
>    'id': '6c3158b7-908a-4472-8379-34296a31009d',
>     'name': 'building bunk bed',
>     'img': 'url'
>  },
>  {
>    'id': '01a29dba-6feb-401c-85eb-77f58d5761d8',
>     'name': 'bathing hamster',
>     'img': 'url'
>  },
>]
>```
- [x] map over this array to create a `TutorialListItem` for each

[^1]: a person who is tutored

**Comment by F-Kirchhoff** [comment]
Kai, this is an amazing first user story. Keep it up! There is only one caveat: The items of your list should not be links (yet) since there isn't anything they can point to.

You could also start with another userstory for displaying the content of a single tutorial, but this approach is fine as well.

**Comment by kai-franke** [comment]
Thanks for your feedback, @F-Kirchhoff !

> The items of your list should not be links (yet) since there isn't anything they can point to.

Done.
