### ISSUE TITLE
Create page / save function / 2

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#22]
## Value Proposition
As a tutor, I want the tutorial data I enter to be saved so that it can be used in the future.

## Description
![capstone-userstory-08](https://user-images.githubusercontent.com/71948045/197994873-291dc051-dd8a-4161-af37-76aca2d62835.png)

## Acceptance Criteria
- [x] when the `finish creating` button is clicked the entered data is saved to a database and the user will be redirected to the `library` page

## Tasks
- [x] create branch
- [x] set up and implement MongoDB
- [x] show database content on `library` page 
- [x] write new tutorial data to database
- [x] implement redirection to `library` page
