### ISSUE TITLE
Picture upload

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#25]
## Value Proposition
As a tutor, when creating a tutorial, I would like to be able to upload my own picture for each step in order to teach the described step in an illustrative way.

## Description
![capstone-userstory-09](https://user-images.githubusercontent.com/71948045/199222711-4a982187-b136-4818-a4c8-7d08b41dbe39.jpg)

## Acceptance Criteria
- [x] displays an `upload` field in each `step` card
- [x] shows a small preview, when an image is selected
- [x] shows the file name of the selected image
- [x] saves the pictures to a database and displays them in their corresponding tutorial steps

## Tasks
- [x] create a new branch
- [x] create `Cloudinary` account
- [x] set up `Cloudinary` to receive and store uploaded pictures
- [x] save corresponding URLs as image source inside tutorial
- [x] create custom `upload` field including preview and name display
- [x] Limit accepted file formats to `.gif, .jpg, .jpeg, .jfif, .pjpeg, .pjp, .png, .webp`

**Comment by philmetscher** [comment]
LGTM. As task 1 I would always write `create feature feat/FEATURENAME`.
Task 4: It's not a button i guess. It's a input-field

**Comment by kai-franke** [comment]
> LGTM. As task 1 I would always write `create feature feat/FEATURENAME`. Task 4: It's not a button i guess. It's a input-field

Very good points! Thanks, @philmetscher ! 😃
