### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#27]
## Value Proposition
As the site owner, I want only authenticated users to be able to create tutorials to limit usage.

## Description
![capstone-userstory-10](https://user-images.githubusercontent.com/71948045/199518571-6dd47eb7-ae50-46b9-ae65-03aae68ad757.png)

## Acceptance Criteria
- [x] the `home` page displays a `login` button
- [x] once clicked, the user gets the possibility to log in with a Github account
- [x] the creation of a tutorial is only possible after logging in
- [x] trying to reach the `create` page while not logged in shows a message `Please log in`

## Tasks
- [x] create a new branch
- [x] create new page `home` 
- [x] create `navItem` for new page and add to navigation
- [x] add headline `Tutorial maker`
- [x] add two buttons for `Login` and `Library`
- [x] create routing for `Library` button to show `library` page
- [x] install nextAuth
- [x] setup nextAuth
- [x] only allow writing to database after user authentification
- [x] write user's email address into database when creating a new tutorial (`author: 'something@email.com'`)

**Comment by sebsch1337** [comment]
Looks great and easy to understand!
