### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#29]
## Value Proposition
As a user, I want to feel welcome on the app's home page and be able to quickly understand what the purpose of the app is so I can easily decide what I want to do next.

## Description
![capstone-userstory-11](https://user-images.githubusercontent.com/71948045/200014409-5d08f94a-e855-4313-9ff3-bc3228dc9ab1.jpg)

## Acceptance Criteria
- [x] `home` page shows a beautiful logo containing the app's name and slogan
- [x] Easy-to-see buttons link to the two main functionalities, the `tutorial library` and `create a tutorial`
- [x] a short `about` text explains the purpose of the app

## Tasks
- [x] create new branch
- [x] create logo and place in `index.js`
- [x] write `about` text and place in `index.js`
- [x] make use of `Button` component and place in `index.js`
- [x] link buttons to `library` and `create` pages

**Comment by gacsphere** [comment]
:shark: Kai, 
I'm excited to see what the final home screen will look like! :tada:

**Comment by kai-franke** [comment]
Thanks, @gacsphere ! Me too. 😄
