### ISSUE TITLE
Tutorial page / motivational card

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#3]
## Value Proposition
As a tutee[^1], I want to be encouraged after I've selected a tutorial in my library to start in a positive learning mood.

## Description
![capstone-userstory-02](https://user-images.githubusercontent.com/71948045/196195987-ec697e0d-57d5-4d6b-9257-85b7ad556fc7.png)

### "My tutorials" page:
- [x] each list item is linked to its tutorial content
- [x] each list item has a small icon that indicates that it is clickable
### Tutorial page / motivational card:
- [x] displays the name of the selected tutorial
- [x] shows a card with the text "Let’s get started! You’re about to learn something new.  That's awesome. Have fun!" and an illustration

## Tasks
- [x] create a new branch
- [x] extend the dummy content with some tutorial steps
- [x] add icon to `TutorialListItem`
- [x] create a `TutorialPage` component
- [x] add a link to `TutorialListItem` that leads to its `TutorialPage` 
- [x] create a `TutorialStartCard` component

[^1]: a person who is tutored

**Comment by F-Kirchhoff** [comment]
Hey Kai, if the start button isn't functionaly for now, you can leave it out please. It is the matter of the next user story then. Otherwise very good user story!

**Comment by kai-franke** [comment]
Thanks for your feedback, @F-Kirchhoff !

That means that my next user story will have the new functionality **and additionally** contains the creation of the `start button` or is there - after I have created the new functionality - **a separate** user story like "I want to be able to start the tutorial after reading the motivational message"?

**Comment by F-Kirchhoff** [comment]
Yes exactly, your next user story is ideal to introduce the button!

**Comment by kai-franke** [comment]
I have implemented the suggested changes and would appreciate a new review. @F-Kirchhoff

**Comment by F-Kirchhoff** [comment]
Top, nothing to add here.
