### ISSUE TITLE
User dashboard

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#31]
## Value Proposition
As a tutor, I would like to have an overview of the tutorials I create to make them easier to find.

## Description
![capstone-userstory-12](https://user-images.githubusercontent.com/71948045/200353911-7f40cfac-219a-448e-86cd-75f0a993f5fb.png)

## Acceptance Criteria
- [x] the navbar contains a new link item `user`
- [x] the new `user` page can only be reached when signed in
- [x] `user` page displays a greeting 'Welcome <user name>'
- [x] `user` page displays a `create tutorial` button
- [x] `user` page displays a list of all tutorials created by the user
- [x] If no tutorials have been created yet, a note will be displayed "You haven't created any tutorials yet." 

## Tasks
- [x] create new branch
- [x] create new page `user`
- [x] limit the accessibility with nextAuth inside `getServerSideProps()`
- [x] add greeting to new page, get <user name> from session object
- [x] add a `create` button by using the `Button` component and link to `create` page
- [x] add headline `Your tutorials` 
- [x] make use of `TutorialList` component to show filtered Tutorial results
- [x] add conditional message "You haven't created any tutorials yet" if `filter()` return an empty array
- [x] add nav item `user` to navbar and link to new page
