### ISSUE TITLE
Delete functionality

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#34]
## Value Proposition
As a tutor, I would like to have the ability to delete tutorials I have created to remove outdated tutorials from distribution.

## Description
![capstone-userstory-13](https://user-images.githubusercontent.com/71948045/200808445-0c755dc9-53c1-42d0-80e2-edce19686054.png)

## Acceptance Criteria
- [x] in `user` page, every tutorial list item displays a `delete` icon
- [x] a modal opens when the `delete` icon is clicked
- [x] the modal displays the question `Do you really want to delete this tutorial?`, a `no, abort` and a `yes, delete` button
- [x] the modal closes when one of the buttons or the background is clicked
- [x] additionally, the tutorial will be deleted when the `yes, delete` button was clicked

## Tasks
- [x] create new branch
- [x] add `delete` icon to tutorial list item
- [x] create functionality to remove a specific document from database collection (accepts tutorial ID)
- [x] create `modal` component and make use of `Button` component to insert the two buttons
- [x] add state for visibility of modal
- [x] add functionality to `yes, delete` button
