### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#36]
## Value Proposition
As a user, I want to have a good user experience to be able to use the app easily and intuitively.

## Description
No wireframe needed

## Acceptance Criteria
- [x] a `create` button is displayed in the final card of each tutorial
- [x] the entire visual appearance of the app is optimized for a good UX
- [x] there is a copy functionality that copies the link of a tutorial to the clipboard

## Tasks
- [x] make a new branch
- [x] make use of `Button` component and add a `create` button to `TutorialEndCard` 
- [x] optimize box-shadow in all pages and components
- [x] replace gif animations by lottifiles
- [x] add `copy` button to `TutorialList`
- [x] add `Modal` to `TutorialList` that is displayed when `copy` button was clicked
- [x] implement the functionality that the URL of a tutorial is copied to the clipboard
- [x] clean up all code
- [x] remove unused imports and fonts
