### ISSUE TITLE
Delete during creation

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#38]
## Value Proposition
As a tutor, I would like to be able to delete individual steps during the process of creating a tutorial in order to remove steps that were created incorrectly.

## Description
![capstone-userstory-14](https://user-images.githubusercontent.com/71948045/202696217-68d63905-955e-4129-83d2-22e1056775c6.png)

## Acceptance Criteria
- [x] each step input form displays a `delete` button
- [x] when the button is clicked, the specific input form is removed
- [x] the numbers of the following cards are adjusted

## Tasks
- [x] create new branch
- [x] add a `delete` button to `FormCard`
- [x] create delete function and add as `onClick` to the `delete` button
- [x] iterate over `inputSteps` state and update the step numbers of remaining input forms
