### ISSUE TITLE
Tutorial page / step card

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#4]
## Value Proposition
As a tutee[^1], I want to go through a tutorial in small individual steps so that I don't get confused by too much new learning content.

## Description
![capstone-userstory-03](https://user-images.githubusercontent.com/71948045/196200552-f5a19b35-8c0f-4713-b80f-bed817a97e0c.png)

### Tutorial page / motivational card:
- [x] shows a `start` button
- [x] when the `start` button is pressed, the card with the first step will be shown.

### Tutorial page / step card:
- [x] shows a card with the image, headline, description text and the number of the current step. 
- [x] shows two buttons which provide the options to go to the next or previous step.

## Tasks
- [x] create a new branch
- [x] create a general `Button` component, that takes its function, name and style as arguments
### Tutorial page / step card:
- [x] create a `TutorialStepCard` component
- [x] use the `Button` component to make a  `prev` and a `next` button
- [x] add the functionality to the buttons that they show the next or previous card
### Tutorial page / motivational card:
- [x] use the `Button` component to make a  `start` button
- [x] add the same functionality to the `start` button as to the `next` button (show the next step)

[^1]: a person who is tutored

**Comment by F-Kirchhoff** [comment]
You can add some more tasks and acceptance criteria, which describe the functionality and implementation of the buttons. Additionally, specify all the components you will create in this user story (aka: do you make two or one component for the navigation buttons?)

**Comment by kai-franke** [comment]
I have implemented the suggested changes and would appreciate a new review. @F-Kirchhoff

**Comment by F-Kirchhoff** [comment]
Amazing, thats how its done!
