### ISSUE TITLE
Jump-to-step functionality

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#42]
## Value Proposition
As a user, I want to be able to jump to a specific step in a tutorial so that I don't have to click back through all the previous steps after an interruption.

## Description
![capstone-userstory-16](https://user-images.githubusercontent.com/71948045/206492488-7b4bad14-999a-4fee-9dcf-81a7e6c8a688.png)

## Acceptance Criteria
- [x] In addition to the current step number, the total number of steps of the tutorial is displayed
- [x] When clicked, the current step number becomes editable and allows a new step number to be entered
- [x] After entering and confirming with Enter or by onBlur, the appropriate step is displayed
- [x] If no new step number is entered or an invalid entry is made, the current step remains displayed

## Tasks
- [x] Create a new branch
- [x] make it work ;)
