### ISSUE TITLE
Tutorial page / success card

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#5]
## Value Proposition
As a tutee[^1], I want to be acknowledged when I have completed all the steps of a tutorial to end my learning experience with a positive feeling.

## Description
![Image](https://user-images.githubusercontent.com/71948045/197178557-13f9dea7-0577-4029-ac40-cbdb92042cc4.jpg)

## Acceptance Criteria
- [x] shows a card with the text "100% – Congratulations! Someone has shared his
- [x] doesn't show the `next` button anymore as this is the end of the tutorial
- [x] shows a `return to library` button, which links to `/tutorials` page

## Tasks
- [x] create a new branch
- [x] create a `TutorialEndCard` component
- [x] add logic to the `next` button so that it does not appear at this last step of the tutorial
- [x] use the `Button` component to add a `return to library` button with its functionality

[^1]: a person who is tutored

**Comment by gacsphere** [comment]
Wonderful! Go on!

I think the option to go back won't be the logical next step for your tutee. Your tutee might want to react to your recommendation to share his/her own knowledge or the tutee wants to close the window or press another button to come back to some kind of overview where she/he can start something new. But that's all the next steps...

**Comment by kai-franke** [comment]
Thank you so much for your feedback, Gesa! I see, you totally understand my project and you totally understand what a keen tutee wants. :) So your suggestions are already in planning stage –  hopefully there will be enough time for me to make it happen. :D

**Comment by kai-franke** [comment]
Dear @gacsphere ! 
Since it was a popular request (and it is easy to implement) I have integrated the "return to library" button into this story.
Would you please give me short review again? 😄

**Comment by gacsphere** [comment]
Sorry @kai-franke, I've seen your request too late :(
But you've done it so well! :rakete:
