### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/capstone-project#6]
## Value Proposition
As a tutee[^1], I want to be able to quickly return to my tutorial collection on the library page at any time and from any page to select another tutorial.

## Description
![capstone-userstory-05-2](https://user-images.githubusercontent.com/71948045/196360931-4af4b5a7-1fe3-4b82-a2ec-702551348a47.jpg)

## Acceptance Criteria
- [x] shows a navbar at the bottom of every page
- [x] navbar displays a book icon and the text "Library", linking to the `LibraryPage`
- [x] on `LibraryPage`, the icon is highlighted

## Tasks
- [x] create a `Navbar` component including an book icon and text "Library"
- [x] integrate Routing
- [x] create Routing path 

[^1]: a person who is tutored

**Comment by CathrinTruchan** [comment]
Nice short user story :) 
Maybe you could add a text to the icon, as it is not completely self-explanatory?

**Comment by kai-franke** [comment]
> Nice short user story :) Maybe you could add a text to the icon, as it is not completely self-explanatory?

That's a very good idea. Thanks Cathrin! :)

**Comment by PhilippWeiss85** [comment]
Same idea as Cathrin. Otherwise lgtm!

**Comment by kai-franke** [comment]
> Same idea as Cathrin. Otherwise lgtm!

Thanks for your feedback, Philipp! :)
